(defun rabbit-mode ()
  (interactive)
  (local-set-key [left] 'undo)
  (local-set-key [right] 'redo)
  (define-key input-decode-map "\e\eOA" [(meta up)])
  (define-key input-decode-map "\e\eOB" [(meta down)])
  (local-set-key [(meta up)] 'scroll-down-command)
  (local-set-key [(meta down)] 'scroll-up-command)
  (local-set-key [up] 'rabbit-previous)
  (local-set-key [down] 'rabbit-forward)
  )

(defun global-rabbit-mode ()
  (interactive)
  (global-set-key [left] 'undo)
  (global-set-key [right] 'redo)
  (define-key input-decode-map "\e\eOA" [(meta up)])
  (define-key input-decode-map "\e\eOB" [(meta down)])
  (global-set-key [(meta up)] 'scroll-down-command)
  (global-set-key [(meta down)] 'scroll-up-command)
  (global-set-key [up] 'rabbit-previous)
  (global-set-key [down] 'rabbit-forward)
  )

(defun rabbit-forward (n)
  (interactive "n Jump to forward line: ")
  (forward-line n))

(defun rabbit-previous (n)
  (interactive "n Jump to previous line: ")
  (previous-line n))


