(defun writing-mode ()
  (interactive)
  (setq buffer-face-mode-face '(:family "dejavu sans mono" :height 150))
  (buffer-face-mode)
  (linum-mode 0)
  (writeroom-mode 1)
  (blink-cursor-mode)
  (visual-line-mode 1)
  (git-gutter-mode -1)
  (flyspell-mode)
  (setq truncate-lines nil)
  (setq-default line-spacing 5)
  (setq global-hl-line-mode nil)
  (setq doom-modeline-enable-word-count t)
  (local-set-key (kbd "M-i d") 'define-word-at-point)
  (local-set-key (kbd "M-i t") 'markdown-toc-generate-or-refresh-toc)
  (local-set-key (kbd "M-i j") 'counsel-semantic-or-imenu)
  (local-set-key (kbd "M-i w") 'write)
  (local-set-key (kbd "M-i <up>") 'magit-push-current-to-upstream)
  (local-set-key (kbd "M-i <down>") 'magit-pull-from-upstream)
  )

(customize-set-variable 'writeroom-mode-line t)

(setq initial-major-mode 'markdown-mode)
