(add-hook 'prog-mode-hook (lambda ()
			    (interactive)
			    (local-set-key (kbd "M-\\") 'company-yasnippet)
			    (local-set-key (kbd "M-i e") 'counsel-flycheck)
			    (local-set-key (kbd "M-i f") 'lsp-execute-code-action)
			    (local-set-key (kbd "M-i r") 'lsp-rename)
			    (local-set-key (kbd "M-i j") 'counsel-semantic-or-imenu)
			    (local-set-key (kbd "M-i w") 'write)
			    (local-set-key (kbd "M-i i") 'lsp-organize-imports)
			    (local-set-key (kbd "M-i g") 'lsp-find-definition)
			    (local-set-key (kbd "M-i t") 'lsp-goto-type-definition)
			    (local-set-key (kbd "M-i c") 'lsp-find-references)
			    (local-set-key (kbd "M-i -") 'revert-buffer)
			    (local-set-key (kbd "M-i <up>") 'magit-push-current-to-upstream)
			    (local-set-key (kbd "M-i <down>") 'magit-pull-from-upstream)
			    ))
