(defun rabbit-mode ()
  (interactive)
  (local-set-key [(meta left)] 'undo-fu-only-undo)
  (local-set-key [(meta right)] 'undo-fu-only-redo)
  (define-key input-decode-map "\e\eOA" [(meta up)])
  (define-key input-decode-map "\e\eOB" [(meta down)])
  ;;(local-set-key [(meta up)] 'scroll-down-command)
  ;;(local-set-key [(meta down)] 'scroll-up-command)
  (local-set-key [(meta up)] 'rabbit-previous)
  (local-set-key [(meta down)] 'rabbit-forward)
  )

(defun global-rabbit-mode ()
  (interactive)
  (global-set-key [(meta left)] 'undo-fu-only-undo)
  (global-set-key [(meta right)] 'undo-fu-only-redo)
  (define-key input-decode-map "\e\eOA" [(meta up)])
  (define-key input-decode-map "\e\eOB" [(meta down)])
  ;;(global-set-key [(meta up)] 'scroll-down-command)
  ;;(global-set-key [(meta down)] 'scroll-up-command)
  (global-set-key [(meta up)] 'rabbit-previous)
  (global-set-key [(meta down)] 'rabbit-forward)
  )

(defun rabbit-forward (n)
  (interactive "n Jump to forward line: ")
  (forward-line n))

(defun rabbit-previous (n)
  (interactive "n Jump to previous line: ")
  (previous-line n))
